name: Deploy static site with LFS

on:
  push:
    branches:
      - main  # 或你使用緊嘅 branch 名

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo with LFS
        uses: actions/checkout@v4
        with:
          lfs: true  # ✅ 關鍵係呢個

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .  # ⬅️ 即係你所有 HTML 同 images 喺 root 底下

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
