name: Deploy static site with LFS

on:
  push:
    branches:
      - main  # ⚠️ 如果你係用 master，就改做 master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo with LFS
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
